### ISSUE TITLE
I'm not authored this commits

### ISSUE THREAD

**Issue by rainlabs** [SamsonPHP/lesson_gallery#4]
What a hell?

**Comment by vitalyiegorov** [comment]
Can you pleasebe more specific? Who you are and what happened?

We have a new employee his name is Artem Ziablytskiy maybe this is an issue

**Comment by rainlabs** [comment]
I receive notifications for your code review comments, but i didn't do it, i don't want to be notified for this

**Comment by vitalyiegorov** [comment]
![image](https://cloud.githubusercontent.com/assets/586558/6313588/15d8e204-b9bd-11e4-8986-b7418a29606b.jpg)
This is your profile image, consider writing to github support, but I repeat again - your second name is the same with our employee, maybe you are relatives? His github account is https://github.com/I70l0teN4ik

**Comment by rainlabs** [comment]
He use my email for some commits, this is a part of git log:

commit 052e5b9524288078cb8514ec3c15a757cb9a55b2
Author: zyablitskiy zyablitskiy@gmail.com
Date:   Fri Feb 20 14:59:01 2015 +0200

```
add config to ignore
```

commit 9b70300182ea61bbb4d49a7ae3724ed08c5b04f5
Author: Artem Ziablytskyi a.zyablitskiy@gmail.com
Date:   Fri Feb 20 14:56:19 2015 +0200

```
Update ActiveRecordConfig.php
```

And github linked this commits with me by email.

**Comment by vitalyiegorov** [comment]
Local git account was configured incorrectly.
